wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682420378.696421
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 19
      - 23
      4: 3.10.9
      5: 0.15.0
      8:
      - 5
    visualize:
      my_histogram:
        panel_type: Vega2
        panel_config:
          panelDefId: wandb/histogram/v0
          fieldSettings:
            value: test
          stringSettings:
            title: Action distribution
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - name: runSets
              args:
              - name: runSets
                value: ${runSets}
              fields:
              - name: id
                fields: []
              - name: name
                fields: []
              - name: _defaultColorIndex
                fields: []
              - name: summaryTable
                args:
                - name: tableKey
                  value: my_histogram_table
                fields: []
log_interval:
  desc: null
  value: 250
