wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682495540.415801
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 19
      - 23
      4: 3.10.9
      5: 0.15.0
      8:
      - 5
log_interval:
  desc: null
  value: 250
